[project]
name = "nf-lecture"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastprogress>=1.0.3",
    "freia>=0.2",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "torchvision>=0.22.1",
]
